[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "reportlab>=4.4.3",
    "scikit-learn>=1.7.1",
    "spacy>=3.8.7",
    "streamlit>=1.48.1",
]
